In [9]:
# data load

,customerid,trips,amount_of_yen,quantity,purchase_period,purchase_recency,purchase_amount_per_trips,regularity,trips_cancellation,trips_cat85099,...,trips_cat22423,trips_cat47566,trips_cat84879,trips_cat20725,trips_cat22720,trips_catpost,trips_cat23203,trips_cat22383,mode_category,tgt
0,12352,8,601.18,188,34,100,75.147500,4.250000,0,0,...,1,0,0,0,0,2,0,0,M,0
1,12359,4,3459.93,961,141,27,864.982500,35.250000,0,1,...,2,1,0,0,1,0,0,0,82613,1
2,12383,5,1238.59,775,146,22,247.718000,29.200000,0,0,...,0,0,0,0,0,4,0,0,84997,1
3,12395,7,1035.90,837,176,0,147.985714,25.142857,0,0,...,1,0,0,0,0,5,0,0,POST,0
4,12408,6,1460.79,725,97,1,243.465000,16.166667,0,1,...,0,0,0,0,0,2,0,0,85099,0

(717, 19)
trips               0
amount_of_yen       0
quantity            0
purchase_period     0
purchase_recency    0
dtype: int64

In [43]:
X.head()

,trips,amount_of_yen,quantity,purchase_period,purchase_recency,purchase_amount_per_trips,regularity,trips_cancellation,trips_cat85099,trips_cat85123,trips_cat22423,trips_cat47566,trips_cat84879,trips_cat20725,trips_cat22720,trips_catpost,trips_cat23203,trips_cat22383,mode_category
0,8,601.18,188,34,100,75.147500,4.250000,0,0,0,1,0,0,0,0,2,0,0,M
1,4,3459.93,961,141,27,864.982500,35.250000,0,1,0,2,1,0,0,1,0,0,0,82613
2,5,1238.59,775,146,22,247.718000,29.200000,0,0,0,0,0,0,0,0,4,0,0,84997
3,7,1035.90,837,176,0,147.985714,25.142857,0,0,0,1,0,0,0,0,5,0,0,POST
4,6,1460.79,725,97,1,243.465000,16.166667,0,1,0,0,0,0,0,0,2,0,0,85099

(717, 334)
trips               0
amount_of_yen       0
quantity            0
purchase_period     0
purchase_recency    0
dtype: int64

(717, 334)
trips               0
amount_of_yen       0
quantity            0
purchase_period     0
purchase_recency    0
dtype: int64

/Users/humu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)

In [171]:
X_ohe_selected =  pd.DataFrame( X_ohe_selected,columns= X_ohe_columns[selector.support_])
print( X_ohe_selected.shape)
X_ohe_selected.head()

(717, 114)

,trips,amount_of_yen,quantity,purchase_period,purchase_recency,purchase_amount_per_trips,regularity,trips_cat85099,trips_cat85123,trips_cat22423,...,mode_category_85118,mode_category_85123,mode_category_85152,mode_category_85194,mode_category_85231,mode_category_85232,mode_category_90200,mode_category_90201,mode_category_M,mode_category_POST
0,8.0,601.18,188.0,34.0,100.0,75.147500,4.250000,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,4.0,3459.93,961.0,141.0,27.0,864.982500,35.250000,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5.0,1238.59,775.0,146.0,22.0,247.718000,29.200000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,7.0,1035.90,837.0,176.0,0.0,147.985714,25.142857,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,6.0,1460.79,725.0,97.0,1.0,243.465000,16.166667,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [175]:

def main():
    # one-hot エンコーディング
  # preprocessing-1: one-hot encoding

df = pd.read_csv('./data/dm_for_model.csv', header=0)
df.head()

ID =  df.iloc[:,0]
y =  df.iloc[:,-1]
X = df.iloc[:,1:-1]
print(X.shape)
print(X.isnull().sum()[:5])
X_ohe = pd.get_dummies(X,dummy_na=True, columns=ohe_cols) 
X_ohe = X_ohe.dropna(axis=1, how='all')
X_ohe_columns =  X_ohe.columns.values

print(X_ohe.shape)
print(X_ohe.isnull().sum()[:5])

from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

imp =  SimpleImputer()
imp.fit(X_ohe)
X_ohe =  pd.DataFrame(imp.transform(X_ohe),columns=X_ohe_columns)
print(X_ohe.shape)
print(X_ohe.isnull().sum()[:5])
from sklearn.feature_selection import RFECV
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib

selector =  RFECV( estimator=RandomForestClassifier(n_estimators= 100,random_state=0),step=0.06)
selector.fit( X_ohe,y)
X_ohe_selected = selector.transform(X_ohe)
    
    if len( file_score)>0:

        dfs = pd.read_csv('./data/'+ file_score + '.csv', header=0)
        IDs = dfs.iloc[:,[0]] 
        Xs = dfs.iloc[:,1:-1]
        Xs_ohe = pd.get_dummies(Xs, dummy_na=True, columns=ohe_cols)
        cols_m = pd.DataFrame(None,columns=X_ohe_columns,dtype=float)

        # consistent with columns set
        Xs_exp = pd.concat([cols_m, Xs_ohe])
        Xs_exp.loc[:,list(set(X_ohe_columns)-set(Xs_ohe.columns.values))] = \
            Xs_exp.loc[:,list(set(X_ohe_columns)-set(Xs_ohe.columns.values))].fillna(0, axis=1)
        Xs_exp = Xs_exp.drop(list(set(Xs_ohe.columns.values)-set(X_ohe_columns)), axis=1)

        # re-order the score data columns
        Xs_exp = Xs_exp.reindex( X_ohe_columns,axis=1)
        Xs_exp = pd.DataFrame(imp.transform(Xs_exp),columns=X_ohe_columns)
        Xs_exp_selected =  Xs_exp.loc[:,X_ohe_columns[selector.support_]]

        # modeling
         # データフレームからarray型に変換する 。また、一元化することによって処理を高速するにする
    clf = Pipeline([('scl',StandardScaler()),('est',GradientBoostingClassifier(random_state=1))])
    clf.fit( X_ohe_selected,y.as_matrix().ravel())
    # 予測モデルを簡単にシリアライズ( データをそのまま保存したり送受信できるように変換すること)と復元することができる。
    joblib.dump( clf,'./model/'+model_name+ '.pkl')
    results = cross_val_score( clf,X_ohe_selected,y,scoring='roc_auc',cv= 5) # rocカーブ面積を計算して再現率　適合率をみる。
    print( 'cv score',np.average( results),'+-',np.std(results))
    # scoreing



    if len(file_score)>0:
        score =  pd.DataFrame(clf.predict_proba(Xs_exp_selected)[:,1],columns=['pred_score'])
        IDs.join(score).to_csv( './data/'+model_name+'_'+file_score+'_with_pred.csv',index= False)


     # model profile
    imp = pd.DataFrame([clf.named_steps['est'].feature_importances_], columns=X_ohe_columns[selector.support_])
    imp.T.to_csv('./data/'+  model_name + '_feature_importances.csv', index=True)

if __name__ == '__main__':
    
    file_model =  'dm_for_model'
    file_score =  ' dm_for_fwd'
    ohe_cols = [' mode_category']
    
    model_name = 'GBC_001'
    clf = Pipeline([('scl',StandardScaler()),('est',GradientBoostingClassifier(random_state=1))])
    
    main()

IndentationError: expected an indented block (<ipython-input-175-6f5d33a38b5d>, line 6)

In [155]:
# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import RFECV
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib

def main():
  # data load
  df = pd.read_csv('./data/'+ file_model + '.csv', header=0)
  ID = df.iloc[:,0] 
  y = df.iloc[:,-1]
  X = df.iloc[:,1:-1]

  # preprocessing-1: one-hot encoding
  X_ohe = pd.get_dummies(X, dummy_na=True, columns=ohe_cols)
  X_ohe = X_ohe.dropna(axis=1, how='all')
  X_ohe_columns = X_ohe.columns.values

  # preprocessing-2: null imputation
  imp = SimpleImputer()
  imp.fit(X_ohe)
  X_ohe = pd.DataFrame(imp.transform(X_ohe), columns=X_ohe_columns)
  print(X_ohe.shape)

  # preprocessing-3: feature selection
  selector = RFECV(estimator=RandomForestClassifier(n_estimators=100,random_state=0), step=0.05)
  selector.fit(X_ohe, y)
  X_ohe_selected = selector.transform(X_ohe)
  X_ohe_selected = pd.DataFrame(X_ohe_selected, columns=X_ohe_columns[selector.support_])
  print(X_ohe_selected.shape)
  X_ohe_selected.head()

  # preprocessing-4: preprocessing of a score data along with a model dataset
  if len(file_score)>0:
      # load score data
      dfs = pd.read_csv('./data/'+ file_score + '.csv', header=0)
      IDs = dfs.iloc[:,[0]] 
      Xs = dfs.iloc[:,1:-1]
      Xs_ohe = pd.get_dummies(Xs, dummy_na=True, columns=ohe_cols)
      cols_m = pd.DataFrame(None, columns=X_ohe_columns, dtype=float)

      # consistent with columns set
      Xs_exp = pd.concat([cols_m, Xs_ohe])
      Xs_exp.loc[:,list(set(X_ohe_columns)-set(Xs_ohe.columns.values))] = \
          Xs_exp.loc[:,list(set(X_ohe_columns)-set(Xs_ohe.columns.values))].fillna(0, axis=1)
      Xs_exp = Xs_exp.drop(list(set(Xs_ohe.columns.values)-set(X_ohe_columns)), axis=1)

      # re-order the score data columns
      Xs_exp = Xs_exp.reindex(X_ohe_columns, axis=1)
      Xs_exp = pd.DataFrame(imp.transform(Xs_exp), columns=X_ohe_columns)
      Xs_exp_selected = Xs_exp.loc[:, X_ohe_columns[selector.support_]]

  # modeling
  clf.fit(X_ohe_selected, y.as_matrix().ravel())
  joblib.dump(clf, './model/'+ model_name + '.pkl')
  results = cross_val_score(clf, X_ohe_selected, y, scoring='roc_auc', cv=5)
  print('cv score:', np.average(results), '+-', np.std(results))

  # scoring
  if len(file_score)>0:
      score = pd.DataFrame(clf.predict_proba(Xs_exp_selected)[:,1], columns=['pred_score'])
      IDs.join(score).to_csv('./data/'+  model_name + '_' + file_score + '_with_pred.csv', index=False)

  # model profile
  imp = pd.DataFrame([clf.named_steps['est'].feature_importances_], columns=X_ohe_columns[selector.support_])
  imp.T.to_csv('./data/'+  model_name + '_feature_importances.csv', index=True)

if __name__ == '__main__':

  # SET PARAMETERS
  file_model = 'dm_for_model'
  file_score = 'dm_for_fwd'
  ohe_cols = ['mode_category']

  # CLASSIFIER
  model_name = 'GBC_001'
  clf = Pipeline([('scl',StandardScaler()),('est',GradientBoostingClassifier(random_state=1))])

  # お手数ですがコメントを外して別途実行下さい
  # model_name = 'RF_001'
  # clf = Pipeline([('scl',StandardScaler()), ('est',RandomForestClassifier(random_state=1))])

  # MAIN PROC
  main()

(717, 334)

/Users/humu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)

(717, 78)

/Users/humu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:50: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

/Users/humu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:61: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

cv score: 0.7110518207282913 +- 0.025779193070101868